version: "3.1"
services:
  prlmntq_etl_news:
    build: .
    image: prlmntq_etl_news
    container_name: prlmntq_etl_news
    restart: always
    ports:
      - 8002:8002
    volumes:
      - .:/usr/src/etl_news
    networks:
      - prlmntq_net

networks:
  prlmntq_net:
    external: true
